### ISSUE TITLE
Gravatar Integration for profile picture

### ISSUE THREAD

**Issue by dmahapatro** [dmahapatro/grails-actuator-ui#5]

**Comment by rpalcolea** [comment]
I can give a little help on this (if you want to of course), just have a few questions:
- There's an old Gravatar plugin (https://github.com/domix/avatarplugin) that isn't available for Grails `3.x`. Do you think it would be a good idea to upgrade it? and then include it in the actuator ui? If not, doing the integration is quite simple... it's just matter of creating the email hash (https://en.gravatar.com/site/implement/images/java/) and generate the URL. The reason for the plugin is more for the community but I don't know if you would like to have extra dependencies on your plugin.
- What about: allow the user specify which property from the `userDomainClassName` to retrieve the email address. I don't see a lot of people rolling their own security implementation on Grails `3.x`. What do you think?

**Comment by dmahapatro** [comment]
@rpalcolea you are more than welcome to help. :)
1. It is a good idea to upgrade the Gravatar plugin. I am not sure what percentage of devs use the plugin today. It will be good to get a metrics for that as well. However, if the plugin abstracts some boiler plate code then it suffices the purpose.
2. Can you elaborate on this one? I am not able to fully get the question. A `username` inside `User` domain class is what being rendered irrespective of whether it is actually an username to email used as username. That functionality in the plugin particularly depends on `spring-security-core plugin`. Refer https://github.com/dmahapatro/grails-actuator-ui/blob/master/actuator-ui/grails-app/views/layouts/actuator.gsp#L64

**Comment by rpalcolea** [comment]
@dmahapatro 

Just published the `3.x` version of the Gravatar plugin: https://github.com/rpalcolea/grails-gravatar I already pushed it to Bintray and asked for the linking in the Grails plugin repo.

This plugin has two things, the TagLib but also an utility `GravatarUrlGenerator` which allows to generate the links without the need of render it in the GSP. I thought this was convenient since not all the people would use a TagLib these days. Obviously, the `GravatarTagLib` uses `GravatarUrlGenerator`.

I'll wait for approval and then I can integrate it in your actuator-ui if you want to.

Regarding the number 2... if I recall, Gravatar only works with emails. Not all the people uses the email as the username. For example your username in a Grails app could be `rpalcolea` but that won't be good enough for gravatar. Sometimes people tend to add a `email` or `emailAddress` field to the `User` class. The idea is to allow the user to specify which property from the `User` class contains the email value.

**Comment by dmahapatro** [comment]
Thanks @rpalcolea, man you are quick in pushing stuff outside the door. I like it. Regarding 2, it does make sense now. That is a good point, I like the idea of specifying a property from user but I believe the plugin can go one step ahead and be smart enough to figure out internally that an email property exists on `User` domain or not (tracing the presence of email constraint, or any String property matching email pattern). If one exists, the use it for Gravatar. If the plugin cannot do it then oviously we can fall back to user input. Thoughts?

**Comment by rpalcolea** [comment]
@dmahapatro Hehe thanks I only try to contribute :)

That sounds much better. What do you mean by user input? I love the idea of implementing logic to determine the proper field. I don't want to fall into a spring security extension 😂

**Comment by dmahapatro** [comment]
I was referring to  _"The idea is to allow the user to specify which property from the User class contains the email value."_

**Comment by rpalcolea** [comment]
Oh great! That makes sense.

I love the idea lets do that
